apiVersion: apps/v1
kind: Deployment
metadata:
  name: olympic-games-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olympic-games-app
  template:
    metadata:
      labels:
        app: olympic-games-app
    spec:
      containers:
        - name: olympic-games-app
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.app.port }}
      imagePullSecrets:
        - name: {{ .Values.app.imagePullSecret }}
