apiVersion: v1
kind: Service
metadata:
  name: olympic-games-app-service
spec:
  selector:
    app: olympic-games-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: LoadBalancer
