apiVersion: apps/v1
kind: Deployment
metadata:
  name: olympic-games-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olympic-games-app
  template:
    metadata:
      labels:
        app: olympic-games-app
    spec:
      containers:
        - name: olympic-games-app
          image: registry.gitlab.com/oc-expert-devops-training/olympic-games-starter/p3-correction
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry-secret
